[package]
name = "eth-lp"
version = "0.1.0"
edition = "2021"
default-run = "api"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name="api"
path="main.rs"

[lib]
path="lib.rs"

[dependencies]
