[tool.poetry]
name = "py"
version = "0.1.0"
description = ""
authors = ["west-github <westcoder@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.7.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
